# file paths
checkpoint_dir: /hpc/scratch/dlehman/CD_checkpoints/gca
test_sets: "v2 inter extra"

output_root: /shared/nl011006/res_ds_ml_restricted/dlehman/state-diff-net/results/
experiment_name: test_gca

# hardware
gpu: true
num_workers: 8

# logging parameters
log_iter: 50
save_fig_iter: 200

cyws:  # model architecture parameters
  attention: gca
  coam_layer_data:
  - 3
  - - 512
    - 256
    - 128
  - - 128
    - 64
    - 32
  decoder_attn_type: scse
  encoder: resnet34
  kernel_sizes:
  - 5
  - 7
  - 11
  pretrained_encoder: true
  self_attention: linear
  n_MSA_layers: 1
  n_SA_heads: 8

img_transforms:
  img_size:
    - 256
    - 256
  normalization: imagenet
  # geometric transforms
  ROI_crops: true
  center_roi: false
  random_crop: false
  max_translation: 0
  rescale: 1