# file paths
train_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Train_states_v2
val_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Val_states_v2
checkpoint_root: /hpc/scratch/dlehman/CD_checkpoints
test_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Val_states_v2

output_root: /shared/nl011006/res_ds_ml_restricted/dlehman/state-diff-net/results
experiment_name: train_config

# change parameters
orientation_thresholds:
- 0.0
- 0.1
parts_diff_thresholds:
- 1
- 6

# learning parameters
loss: ce
optimizer: adam
batch_size: 64

lr: 1.0e-05
warmup_epochs: 15
lr_policy: cosine
T_0: 300
T_mult: 2
init_type: kaiming
max_epochs: 315

# hardware
gpu: true
num_workers: 8

# to resume training
resume_ckpt_path: ''
resume_results_dir: ''

# logging parameters
log_iter: 50
save_fig_iter: 1
save_ckpt: false

cyws:  # model architecture parameters
  attention: coam
  coam_layer_data:
  - 3
  - - 512
    - 256
    - 128
  - - 128
    - 64
    - 32
  decoder_attn_type: scse
  encoder: resnet34
  kernel_sizes:
  - 5
  - 7
  - 11
  pretrained_encoder: true
  self_attention: None
  n_MSA_layers: 0
  n_SA_heads: 8

img_transforms:
  img_size:
    - 256
    - 256
  normalization: imagenet
  # geometric transforms
  ROI_crops: true
  center_roi: false
  random_crop: false
  max_translation: 0
  rescale: 1
  rotation: true
  shear: 20
  hflip_probability: 0.5
  vflip_probability: 0.2
  # color augmentation
  brightness: 0.1
  contrast: 0.1
  saturation: 0.6
  hue: 0.1
  g_kernel_size: 5
  g_sigma_h: 1
  g_sigma_l: 0.01