T_0: 100
T_mult: 2
batch_size: 64
checkpoint_root: /hpc/scratch/dlehman/CD_checkpoints
cyws:
  attention: gca
  coam_layer_data:
  - 3
  - - 512
    - 256
    - 128
  - - 128
    - 64
    - 32
  decoder_attn_type: scse
  encoder: resnet34
  kernel_sizes:
  - 5
  - 7
  - 11
  n_MSA_layers: 1
  n_SA_heads: 8
  pretrained_encoder: true
  self_attention: linear
experiment_name: example
fda:
  beta_max: 0.005
  beta_min: 0.005
  frac_imgs_w_fda: 0.5
gpu: true
img_transforms:
  ROI_crops: true
  brightness: 0.5
  center_roi: false
  contrast: 0.5
  frac_random_background: 0.3
  g_kernel_size: 5
  g_sigma_h: 1
  g_sigma_l: 0.01
  gradually_augment: false
  hflip_probability: 0.5
  hue: 0.1
  img_size:
  - 256
  - 256
  max_translation: 0
  normalization: imagenet
  random_crop: false
  rescale: 1
  rotation: true
  saturation: 0.6
  shear: 12
  vflip_probability: 0.2
init_type: kaiming
log_iter: 50
loss: ce
lr: 1.0e-05
lr_policy: cosine
max_epochs: 315
num_workers: 8
optimizer: adam
orientation_thresholds:
- 0.0
- 0.1
output_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/state-diff-net/results/ft_fda50%_moreaug_w_shear_randbg
output_root: /shared/nl011006/res_ds_ml_restricted/dlehman/state-diff-net/results
parts_diff_thresholds:
- 1
- 6
resume_ckpt_path: /hpc/scratch/dlehman/CD_checkpoints/gca_fda50%_moreaug/last_ckpt.pt
resume_results_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/state-diff-net/results/gca_fda50%_moreaug
save_ckpt: true
save_fig_iter: 200
train_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Train_states_v2
val_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Val_states_v2
vis_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/state-diff-net/results/ft_fda50%_moreaug_w_shear_randbg/visualize
warmup_epochs: 15
