checkpoint_root: ./checkpoints
output_root: ./results

eval_freq: 100
freeze_encoder: false
gpu: true
init_type: kaiming
log_iter: 50
loss: ce
lr: 1.0e-05
lr_gamma: 0.9
lr_policy: cosine
max_epochs: 315
net_G: cyws
num_workers: 8
optimizer: adam
orientation_thresholds:
- 0.0
- 0.1
experiment_name: ''
resume_ckpt_path: ''
resume_results_dir: ''
save_ckpt: true
save_fig_iter: 300
state_diff_thresholds:
- 1
- 6
train_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Train_states_v2
val_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Val_states_v2
warmup_epochs: 15
T_0: 300
T_mult: 2
batch_size: 64

cyws:
  attention: noam
  coam_layer_data:
  - 3
  - - 512
    - 256
    - 128
  - - 128
    - 64
    - 32
  decoder_attn_type: scse
  encoder: resnet34
  kernel_sizes:
  - 5
  - 7
  - 11
  n_MSA_layers: 1
  n_SA_heads: 8
  pretrained_encoder: true
  self_attention: linear

img_transforms:
  ROI_crops: true
  brightness: 0.1
  center_roi: false
  contrast: 0.1
  g_kernel_size: 5.0
  g_sigma_h: 1.0
  g_sigma_l: 0.01
  hflip_probability: 0.5
  hue: 0.1
  img_size:
  - 256
  - 256
  max_translation: 0.0
  normalization: imagenet
  random_crop: false
  rescale: 1.0
  rotation: true
  saturation: 0.6
  shear: 0
  vflip_probability: 0.2
