T_0: 300
T_mult: 2
batch_size: 64
checkpoint_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/assembly-error-localization/results/roi_v2_dataset_linearMSA_ft_jitter/checkpoints
checkpoint_root: /hpc/scratch/dlehman/CD_checkpoints
cyws:
  attention: coam
  coam_layer_data:
  - 3
  - - 512
    - 256
    - 128
  - - 128
    - 64
    - 32
  concat_fs1_to_self_attention: false
  decoder_attn_type: scse
  encoder: resnet34
  kernel_sizes:
  - 5
  - 7
  - 11
  n_MSA_layers: 1
  n_SA_heads: 8
  pretrained_encoder: true
  self_attention: linear
  self_attention_in_CA: false
data_augmentations:
  ROI_crops: true
  brightness: 0.5
  center_roi: false
  contrast: 0.5
  g_kernel_size: 5.0
  g_sigma_h: 1.0
  g_sigma_l: 0.01
  hflip_probability: 0.5
  hue: 0.1
  img_size:
  - 256
  - 256
  max_translation: 0.0
  normalization: imagenet
  random_crop: false
  rescale: 1.0
  rotation: true
  saturation: 0.6
  shear: 0
  vflip_probability: 0.2
  wheel_jitter: false
eval_freq: 100
freeze_encoder: false
gpu: true
init_type: kaiming
log_iter: 50
loss: ce
lr: 1.0e-05
lr_gamma: 0.9
lr_policy: linear
max_epochs: 100
net_G: cyws
num_workers: 8
optimizer: adam
orientation_thresholds:
- 0.0
- 0.1
output_dim: 2
output_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/assembly-error-localization/results/roi_v2_dataset_linearMSA_ft_jitter
output_root: /shared/nl011006/res_ds_ml_restricted/dlehman/assembly-error-localization/results
project_name: roi_v2_dataset_linearMSA_ft_jitter
resume_ckpt_path: /shared/nl011006/res_ds_ml_restricted/dlehman/assembly-error-localization/results/roi_v2_dataset_linearMSA/checkpoints/last_ckpt.pt
resume_results_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/assembly-error-localization/results/roi_v2_dataset_linearMSA
save_ckpt: true
save_fig_iter: 300
state_diff_thresholds:
- 1
- 6
test_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Val_states_set_200x1000
train_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Train_states_v2
val_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/SyntheticData/Val_states_v2
vis_dir: /shared/nl011006/res_ds_ml_restricted/dlehman/assembly-error-localization/results/roi_v2_dataset_linearMSA_ft_jitter/visualize
warmup_epochs: 5